/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminSettingsRouteImport } from './routes/_admin/settings'
import { Route as AdminSalonsRouteImport } from './routes/_admin/salons'
import { Route as AdminOverviewRouteImport } from './routes/_admin/overview'
import { Route as AdminCatalogPresetsRouteImport } from './routes/_admin/catalog-presets'
import { Route as AdminAuditLogRouteImport } from './routes/_admin/audit-log'
import { Route as AdminSalonsIndexRouteImport } from './routes/_admin/salons.index'
import { Route as AdminSalonsSalonIdRouteImport } from './routes/_admin/salons.$salonId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalonsRoute = AdminSalonsRouteImport.update({
  id: '/salons',
  path: '/salons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogPresetsRoute = AdminCatalogPresetsRouteImport.update({
  id: '/catalog-presets',
  path: '/catalog-presets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalonsIndexRoute = AdminSalonsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSalonsRoute,
} as any)
const AdminSalonsSalonIdRoute = AdminSalonsSalonIdRouteImport.update({
  id: '/$salonId',
  path: '/$salonId',
  getParentRoute: () => AdminSalonsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit-log': typeof AdminAuditLogRoute
  '/catalog-presets': typeof AdminCatalogPresetsRoute
  '/overview': typeof AdminOverviewRoute
  '/salons': typeof AdminSalonsRouteWithChildren
  '/settings': typeof AdminSettingsRoute
  '/salons/$salonId': typeof AdminSalonsSalonIdRoute
  '/salons/': typeof AdminSalonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit-log': typeof AdminAuditLogRoute
  '/catalog-presets': typeof AdminCatalogPresetsRoute
  '/overview': typeof AdminOverviewRoute
  '/settings': typeof AdminSettingsRoute
  '/salons/$salonId': typeof AdminSalonsSalonIdRoute
  '/salons': typeof AdminSalonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/audit-log': typeof AdminAuditLogRoute
  '/_admin/catalog-presets': typeof AdminCatalogPresetsRoute
  '/_admin/overview': typeof AdminOverviewRoute
  '/_admin/salons': typeof AdminSalonsRouteWithChildren
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/salons/$salonId': typeof AdminSalonsSalonIdRoute
  '/_admin/salons/': typeof AdminSalonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit-log'
    | '/catalog-presets'
    | '/overview'
    | '/salons'
    | '/settings'
    | '/salons/$salonId'
    | '/salons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/audit-log'
    | '/catalog-presets'
    | '/overview'
    | '/settings'
    | '/salons/$salonId'
    | '/salons'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/audit-log'
    | '/_admin/catalog-presets'
    | '/_admin/overview'
    | '/_admin/salons'
    | '/_admin/settings'
    | '/_admin/salons/$salonId'
    | '/_admin/salons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/salons': {
      id: '/_admin/salons'
      path: '/salons'
      fullPath: '/salons'
      preLoaderRoute: typeof AdminSalonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/overview': {
      id: '/_admin/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/catalog-presets': {
      id: '/_admin/catalog-presets'
      path: '/catalog-presets'
      fullPath: '/catalog-presets'
      preLoaderRoute: typeof AdminCatalogPresetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/audit-log': {
      id: '/_admin/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/salons/': {
      id: '/_admin/salons/'
      path: '/'
      fullPath: '/salons/'
      preLoaderRoute: typeof AdminSalonsIndexRouteImport
      parentRoute: typeof AdminSalonsRoute
    }
    '/_admin/salons/$salonId': {
      id: '/_admin/salons/$salonId'
      path: '/$salonId'
      fullPath: '/salons/$salonId'
      preLoaderRoute: typeof AdminSalonsSalonIdRouteImport
      parentRoute: typeof AdminSalonsRoute
    }
  }
}

interface AdminSalonsRouteChildren {
  AdminSalonsSalonIdRoute: typeof AdminSalonsSalonIdRoute
  AdminSalonsIndexRoute: typeof AdminSalonsIndexRoute
}

const AdminSalonsRouteChildren: AdminSalonsRouteChildren = {
  AdminSalonsSalonIdRoute: AdminSalonsSalonIdRoute,
  AdminSalonsIndexRoute: AdminSalonsIndexRoute,
}

const AdminSalonsRouteWithChildren = AdminSalonsRoute._addFileChildren(
  AdminSalonsRouteChildren,
)

interface AdminRouteChildren {
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminCatalogPresetsRoute: typeof AdminCatalogPresetsRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminSalonsRoute: typeof AdminSalonsRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminCatalogPresetsRoute: AdminCatalogPresetsRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminSalonsRoute: AdminSalonsRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
