/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminAuditLogRouteImport } from './routes/_admin/audit-log'
import { Route as AdminCatalogPresetsRouteImport } from './routes/_admin/catalog-presets'
import { Route as AdminOverviewRouteImport } from './routes/_admin/overview'
import { Route as AdminSalonsRouteImport } from './routes/_admin/salons'
import { Route as AdminSettingsRouteImport } from './routes/_admin/settings'
import { Route as AdminSupportTicketsRouteImport } from './routes/_admin/support-tickets'
import { Route as AdminSalonsIndexRouteImport } from './routes/_admin/salons.index'
import { Route as AdminSalonsSalonIdRouteImport } from './routes/_admin/salons.$salonId'
import { Route as AdminSupportTicketsIndexRouteImport } from './routes/_admin/support-tickets.index'
import { Route as AdminSupportTicketsTicketIdRouteImport } from './routes/_admin/support-tickets.$ticketId'
import { Route as AdminSalonsSalonIdClientsRouteImport } from './routes/_admin/salons.$salonId.clients'
import { Route as AdminSalonsSalonIdEditRouteImport } from './routes/_admin/salons.$salonId.edit'
import { Route as AdminSalonsSalonIdHandoffRouteImport } from './routes/_admin/salons.$salonId.handoff'
import { Route as AdminSalonsSalonIdHoursRouteImport } from './routes/_admin/salons.$salonId.hours'
import { Route as AdminSalonsSalonIdPresenceRouteImport } from './routes/_admin/salons.$salonId.presence'
import { Route as AdminSalonsSalonIdRequestsRouteImport } from './routes/_admin/salons.$salonId.requests'
import { Route as AdminSalonsSalonIdServicesRouteImport } from './routes/_admin/salons.$salonId.services'
import { Route as AdminSalonsSalonIdStaffRouteImport } from './routes/_admin/salons.$salonId.staff'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogRoute = AdminAuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogPresetsRoute = AdminCatalogPresetsRouteImport.update({
  id: '/catalog-presets',
  path: '/catalog-presets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOverviewRoute = AdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalonsRoute = AdminSalonsRouteImport.update({
  id: '/salons',
  path: '/salons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportTicketsRoute = AdminSupportTicketsRouteImport.update({
  id: '/support-tickets',
  path: '/support-tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalonsIndexRoute = AdminSalonsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSalonsRoute,
} as any)
const AdminSalonsSalonIdRoute = AdminSalonsSalonIdRouteImport.update({
  id: '/$salonId',
  path: '/$salonId',
  getParentRoute: () => AdminSalonsRoute,
} as any)
const AdminSupportTicketsIndexRoute =
  AdminSupportTicketsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminSupportTicketsRoute,
  } as any)
const AdminSupportTicketsTicketIdRoute =
  AdminSupportTicketsTicketIdRouteImport.update({
    id: '/$ticketId',
    path: '/$ticketId',
    getParentRoute: () => AdminSupportTicketsRoute,
  } as any)
const AdminSalonsSalonIdClientsRoute =
  AdminSalonsSalonIdClientsRouteImport.update({
    id: '/clients',
    path: '/clients',
    getParentRoute: () => AdminSalonsSalonIdRoute,
  } as any)
const AdminSalonsSalonIdEditRoute = AdminSalonsSalonIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminSalonsSalonIdRoute,
} as any)
const AdminSalonsSalonIdHandoffRoute =
  AdminSalonsSalonIdHandoffRouteImport.update({
    id: '/handoff',
    path: '/handoff',
    getParentRoute: () => AdminSalonsSalonIdRoute,
  } as any)
const AdminSalonsSalonIdHoursRoute = AdminSalonsSalonIdHoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => AdminSalonsSalonIdRoute,
} as any)
const AdminSalonsSalonIdPresenceRoute =
  AdminSalonsSalonIdPresenceRouteImport.update({
    id: '/presence',
    path: '/presence',
    getParentRoute: () => AdminSalonsSalonIdRoute,
  } as any)
const AdminSalonsSalonIdRequestsRoute =
  AdminSalonsSalonIdRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => AdminSalonsSalonIdRoute,
  } as any)
const AdminSalonsSalonIdServicesRoute =
  AdminSalonsSalonIdServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AdminSalonsSalonIdRoute,
  } as any)
const AdminSalonsSalonIdStaffRoute = AdminSalonsSalonIdStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AdminSalonsSalonIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit-log': typeof AdminAuditLogRoute
  '/catalog-presets': typeof AdminCatalogPresetsRoute
  '/overview': typeof AdminOverviewRoute
  '/salons': typeof AdminSalonsRouteWithChildren
  '/settings': typeof AdminSettingsRoute
  '/support-tickets': typeof AdminSupportTicketsRouteWithChildren
  '/salons/$salonId': typeof AdminSalonsSalonIdRouteWithChildren
  '/support-tickets/$ticketId': typeof AdminSupportTicketsTicketIdRoute
  '/salons/': typeof AdminSalonsIndexRoute
  '/support-tickets/': typeof AdminSupportTicketsIndexRoute
  '/salons/$salonId/clients': typeof AdminSalonsSalonIdClientsRoute
  '/salons/$salonId/edit': typeof AdminSalonsSalonIdEditRoute
  '/salons/$salonId/handoff': typeof AdminSalonsSalonIdHandoffRoute
  '/salons/$salonId/hours': typeof AdminSalonsSalonIdHoursRoute
  '/salons/$salonId/presence': typeof AdminSalonsSalonIdPresenceRoute
  '/salons/$salonId/requests': typeof AdminSalonsSalonIdRequestsRoute
  '/salons/$salonId/services': typeof AdminSalonsSalonIdServicesRoute
  '/salons/$salonId/staff': typeof AdminSalonsSalonIdStaffRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/audit-log': typeof AdminAuditLogRoute
  '/catalog-presets': typeof AdminCatalogPresetsRoute
  '/overview': typeof AdminOverviewRoute
  '/settings': typeof AdminSettingsRoute
  '/salons/$salonId': typeof AdminSalonsSalonIdRouteWithChildren
  '/support-tickets/$ticketId': typeof AdminSupportTicketsTicketIdRoute
  '/salons': typeof AdminSalonsIndexRoute
  '/support-tickets': typeof AdminSupportTicketsIndexRoute
  '/salons/$salonId/clients': typeof AdminSalonsSalonIdClientsRoute
  '/salons/$salonId/edit': typeof AdminSalonsSalonIdEditRoute
  '/salons/$salonId/handoff': typeof AdminSalonsSalonIdHandoffRoute
  '/salons/$salonId/hours': typeof AdminSalonsSalonIdHoursRoute
  '/salons/$salonId/presence': typeof AdminSalonsSalonIdPresenceRoute
  '/salons/$salonId/requests': typeof AdminSalonsSalonIdRequestsRoute
  '/salons/$salonId/services': typeof AdminSalonsSalonIdServicesRoute
  '/salons/$salonId/staff': typeof AdminSalonsSalonIdStaffRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/audit-log': typeof AdminAuditLogRoute
  '/_admin/catalog-presets': typeof AdminCatalogPresetsRoute
  '/_admin/overview': typeof AdminOverviewRoute
  '/_admin/salons': typeof AdminSalonsRouteWithChildren
  '/_admin/settings': typeof AdminSettingsRoute
  '/_admin/support-tickets': typeof AdminSupportTicketsRouteWithChildren
  '/_admin/salons/$salonId': typeof AdminSalonsSalonIdRouteWithChildren
  '/_admin/support-tickets/$ticketId': typeof AdminSupportTicketsTicketIdRoute
  '/_admin/salons/': typeof AdminSalonsIndexRoute
  '/_admin/support-tickets/': typeof AdminSupportTicketsIndexRoute
  '/_admin/salons/$salonId/clients': typeof AdminSalonsSalonIdClientsRoute
  '/_admin/salons/$salonId/edit': typeof AdminSalonsSalonIdEditRoute
  '/_admin/salons/$salonId/handoff': typeof AdminSalonsSalonIdHandoffRoute
  '/_admin/salons/$salonId/hours': typeof AdminSalonsSalonIdHoursRoute
  '/_admin/salons/$salonId/presence': typeof AdminSalonsSalonIdPresenceRoute
  '/_admin/salons/$salonId/requests': typeof AdminSalonsSalonIdRequestsRoute
  '/_admin/salons/$salonId/services': typeof AdminSalonsSalonIdServicesRoute
  '/_admin/salons/$salonId/staff': typeof AdminSalonsSalonIdStaffRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit-log'
    | '/catalog-presets'
    | '/overview'
    | '/salons'
    | '/settings'
    | '/support-tickets'
    | '/salons/$salonId'
    | '/support-tickets/$ticketId'
    | '/salons/'
    | '/support-tickets/'
    | '/salons/$salonId/clients'
    | '/salons/$salonId/edit'
    | '/salons/$salonId/handoff'
    | '/salons/$salonId/hours'
    | '/salons/$salonId/presence'
    | '/salons/$salonId/requests'
    | '/salons/$salonId/services'
    | '/salons/$salonId/staff'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/audit-log'
    | '/catalog-presets'
    | '/overview'
    | '/settings'
    | '/salons/$salonId'
    | '/support-tickets/$ticketId'
    | '/salons'
    | '/support-tickets'
    | '/salons/$salonId/clients'
    | '/salons/$salonId/edit'
    | '/salons/$salonId/handoff'
    | '/salons/$salonId/hours'
    | '/salons/$salonId/presence'
    | '/salons/$salonId/requests'
    | '/salons/$salonId/services'
    | '/salons/$salonId/staff'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/login'
    | '/_admin/audit-log'
    | '/_admin/catalog-presets'
    | '/_admin/overview'
    | '/_admin/salons'
    | '/_admin/settings'
    | '/_admin/support-tickets'
    | '/_admin/salons/$salonId'
    | '/_admin/support-tickets/$ticketId'
    | '/_admin/salons/'
    | '/_admin/support-tickets/'
    | '/_admin/salons/$salonId/clients'
    | '/_admin/salons/$salonId/edit'
    | '/_admin/salons/$salonId/handoff'
    | '/_admin/salons/$salonId/hours'
    | '/_admin/salons/$salonId/presence'
    | '/_admin/salons/$salonId/requests'
    | '/_admin/salons/$salonId/services'
    | '/_admin/salons/$salonId/staff'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/audit-log': {
      id: '/_admin/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AdminAuditLogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/catalog-presets': {
      id: '/_admin/catalog-presets'
      path: '/catalog-presets'
      fullPath: '/catalog-presets'
      preLoaderRoute: typeof AdminCatalogPresetsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/overview': {
      id: '/_admin/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AdminOverviewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/salons': {
      id: '/_admin/salons'
      path: '/salons'
      fullPath: '/salons'
      preLoaderRoute: typeof AdminSalonsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/settings': {
      id: '/_admin/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/support-tickets': {
      id: '/_admin/support-tickets'
      path: '/support-tickets'
      fullPath: '/support-tickets'
      preLoaderRoute: typeof AdminSupportTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/salons/': {
      id: '/_admin/salons/'
      path: '/'
      fullPath: '/salons/'
      preLoaderRoute: typeof AdminSalonsIndexRouteImport
      parentRoute: typeof AdminSalonsRoute
    }
    '/_admin/salons/$salonId': {
      id: '/_admin/salons/$salonId'
      path: '/$salonId'
      fullPath: '/salons/$salonId'
      preLoaderRoute: typeof AdminSalonsSalonIdRouteImport
      parentRoute: typeof AdminSalonsRoute
    }
    '/_admin/support-tickets/': {
      id: '/_admin/support-tickets/'
      path: '/'
      fullPath: '/support-tickets/'
      preLoaderRoute: typeof AdminSupportTicketsIndexRouteImport
      parentRoute: typeof AdminSupportTicketsRoute
    }
    '/_admin/support-tickets/$ticketId': {
      id: '/_admin/support-tickets/$ticketId'
      path: '/$ticketId'
      fullPath: '/support-tickets/$ticketId'
      preLoaderRoute: typeof AdminSupportTicketsTicketIdRouteImport
      parentRoute: typeof AdminSupportTicketsRoute
    }
    '/_admin/salons/$salonId/clients': {
      id: '/_admin/salons/$salonId/clients'
      path: '/clients'
      fullPath: '/salons/$salonId/clients'
      preLoaderRoute: typeof AdminSalonsSalonIdClientsRouteImport
      parentRoute: typeof AdminSalonsSalonIdRoute
    }
    '/_admin/salons/$salonId/edit': {
      id: '/_admin/salons/$salonId/edit'
      path: '/edit'
      fullPath: '/salons/$salonId/edit'
      preLoaderRoute: typeof AdminSalonsSalonIdEditRouteImport
      parentRoute: typeof AdminSalonsSalonIdRoute
    }
    '/_admin/salons/$salonId/handoff': {
      id: '/_admin/salons/$salonId/handoff'
      path: '/handoff'
      fullPath: '/salons/$salonId/handoff'
      preLoaderRoute: typeof AdminSalonsSalonIdHandoffRouteImport
      parentRoute: typeof AdminSalonsSalonIdRoute
    }
    '/_admin/salons/$salonId/hours': {
      id: '/_admin/salons/$salonId/hours'
      path: '/hours'
      fullPath: '/salons/$salonId/hours'
      preLoaderRoute: typeof AdminSalonsSalonIdHoursRouteImport
      parentRoute: typeof AdminSalonsSalonIdRoute
    }
    '/_admin/salons/$salonId/presence': {
      id: '/_admin/salons/$salonId/presence'
      path: '/presence'
      fullPath: '/salons/$salonId/presence'
      preLoaderRoute: typeof AdminSalonsSalonIdPresenceRouteImport
      parentRoute: typeof AdminSalonsSalonIdRoute
    }
    '/_admin/salons/$salonId/requests': {
      id: '/_admin/salons/$salonId/requests'
      path: '/requests'
      fullPath: '/salons/$salonId/requests'
      preLoaderRoute: typeof AdminSalonsSalonIdRequestsRouteImport
      parentRoute: typeof AdminSalonsSalonIdRoute
    }
    '/_admin/salons/$salonId/services': {
      id: '/_admin/salons/$salonId/services'
      path: '/services'
      fullPath: '/salons/$salonId/services'
      preLoaderRoute: typeof AdminSalonsSalonIdServicesRouteImport
      parentRoute: typeof AdminSalonsSalonIdRoute
    }
    '/_admin/salons/$salonId/staff': {
      id: '/_admin/salons/$salonId/staff'
      path: '/staff'
      fullPath: '/salons/$salonId/staff'
      preLoaderRoute: typeof AdminSalonsSalonIdStaffRouteImport
      parentRoute: typeof AdminSalonsSalonIdRoute
    }
  }
}

interface AdminSalonsSalonIdRouteChildren {
  AdminSalonsSalonIdClientsRoute: typeof AdminSalonsSalonIdClientsRoute
  AdminSalonsSalonIdEditRoute: typeof AdminSalonsSalonIdEditRoute
  AdminSalonsSalonIdHandoffRoute: typeof AdminSalonsSalonIdHandoffRoute
  AdminSalonsSalonIdHoursRoute: typeof AdminSalonsSalonIdHoursRoute
  AdminSalonsSalonIdPresenceRoute: typeof AdminSalonsSalonIdPresenceRoute
  AdminSalonsSalonIdRequestsRoute: typeof AdminSalonsSalonIdRequestsRoute
  AdminSalonsSalonIdServicesRoute: typeof AdminSalonsSalonIdServicesRoute
  AdminSalonsSalonIdStaffRoute: typeof AdminSalonsSalonIdStaffRoute
}

const AdminSalonsSalonIdRouteChildren: AdminSalonsSalonIdRouteChildren = {
  AdminSalonsSalonIdClientsRoute: AdminSalonsSalonIdClientsRoute,
  AdminSalonsSalonIdEditRoute: AdminSalonsSalonIdEditRoute,
  AdminSalonsSalonIdHandoffRoute: AdminSalonsSalonIdHandoffRoute,
  AdminSalonsSalonIdHoursRoute: AdminSalonsSalonIdHoursRoute,
  AdminSalonsSalonIdPresenceRoute: AdminSalonsSalonIdPresenceRoute,
  AdminSalonsSalonIdRequestsRoute: AdminSalonsSalonIdRequestsRoute,
  AdminSalonsSalonIdServicesRoute: AdminSalonsSalonIdServicesRoute,
  AdminSalonsSalonIdStaffRoute: AdminSalonsSalonIdStaffRoute,
}

const AdminSalonsSalonIdRouteWithChildren =
  AdminSalonsSalonIdRoute._addFileChildren(AdminSalonsSalonIdRouteChildren)

interface AdminSalonsRouteChildren {
  AdminSalonsSalonIdRoute: typeof AdminSalonsSalonIdRouteWithChildren
  AdminSalonsIndexRoute: typeof AdminSalonsIndexRoute
}

const AdminSalonsRouteChildren: AdminSalonsRouteChildren = {
  AdminSalonsSalonIdRoute: AdminSalonsSalonIdRouteWithChildren,
  AdminSalonsIndexRoute: AdminSalonsIndexRoute,
}

const AdminSalonsRouteWithChildren = AdminSalonsRoute._addFileChildren(
  AdminSalonsRouteChildren,
)

interface AdminSupportTicketsRouteChildren {
  AdminSupportTicketsTicketIdRoute: typeof AdminSupportTicketsTicketIdRoute
  AdminSupportTicketsIndexRoute: typeof AdminSupportTicketsIndexRoute
}

const AdminSupportTicketsRouteChildren: AdminSupportTicketsRouteChildren = {
  AdminSupportTicketsTicketIdRoute: AdminSupportTicketsTicketIdRoute,
  AdminSupportTicketsIndexRoute: AdminSupportTicketsIndexRoute,
}

const AdminSupportTicketsRouteWithChildren =
  AdminSupportTicketsRoute._addFileChildren(AdminSupportTicketsRouteChildren)

interface AdminRouteChildren {
  AdminAuditLogRoute: typeof AdminAuditLogRoute
  AdminCatalogPresetsRoute: typeof AdminCatalogPresetsRoute
  AdminOverviewRoute: typeof AdminOverviewRoute
  AdminSalonsRoute: typeof AdminSalonsRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportTicketsRoute: typeof AdminSupportTicketsRouteWithChildren
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAuditLogRoute: AdminAuditLogRoute,
  AdminCatalogPresetsRoute: AdminCatalogPresetsRoute,
  AdminOverviewRoute: AdminOverviewRoute,
  AdminSalonsRoute: AdminSalonsRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportTicketsRoute: AdminSupportTicketsRouteWithChildren,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
