import { mkdir, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  appointmentStatusPalettes,
  calendarColorOptions,
  fontFamily,
  radiusPx,
  radiusRem,
  saloora,
  semanticDark,
  semanticLight,
} from '../src/index'

const root = dirname(dirname(fileURLToPath(import.meta.url)))
const generatedDir = join(root, 'generated')

type TokenValue = { oklch: string; hex: string }

function cssVars(prefix: string, tokens: Record<string, TokenValue>): string[] {
  return Object.entries(tokens).map(
    ([key, token]) => `  --${prefix}${kebab(key)}: ${token.oklch};`,
  )
}

function kebab(value: string): string {
  return value.replace(/[A-Z]/g, (char) => `-${char.toLowerCase()}`)
}

function jsonReadyTokens(tokens: Record<string, TokenValue>) {
  return Object.fromEntries(
    Object.entries(tokens).map(([key, token]) => [key, token.hex]),
  )
}

const lightCalendarVars = calendarColorOptions.map(
  (option, index) => `  --staff-${index + 1}: var(--calendar-${option.id});`,
)
const darkCalendarVars = calendarColorOptions.map(
  (option, index) => `  --staff-${index + 1}: var(--calendar-${option.id});`,
)

const themeColorVars = [
  ...Object.keys(saloora).map(
    (key) => `  --color-saloora-${kebab(key)}: var(--saloora-${kebab(key)});`,
  ),
  ...calendarColorOptions.map(
    (option, index) =>
      `  --color-staff-${index + 1}: var(--staff-${index + 1});`,
  ),
  ...Object.keys(semanticLight).map(
    (key) => `  --color-${kebab(key)}: var(--${kebab(key)});`,
  ),
  ...['chart-1', 'chart-2', 'chart-3', 'chart-4', 'chart-5'].map(
    (key) => `  --color-${key}: var(--${key});`,
  ),
  ...[
    'sidebar',
    'sidebar-foreground',
    'sidebar-primary',
    'sidebar-primary-foreground',
    'sidebar-accent',
    'sidebar-accent-foreground',
    'sidebar-border',
    'sidebar-ring',
  ].map((key) => `  --color-${key}: var(--${key});`),
  ...Object.keys(appointmentStatusPalettes).flatMap((status) => [
    `  --color-status-${status}-background: var(--status-${status}-background);`,
    `  --color-status-${status}-foreground: var(--status-${status}-foreground);`,
    `  --color-status-${status}-border: var(--status-${status}-border);`,
  ]),
]

const css = `/* This file is generated by @repo/brand-tokens. Do not edit by hand. */

:root {
${cssVars('saloora-', saloora).join('\n')}
${cssVars('', semanticLight).join('\n')}
  --chart-1: var(--saloora-plum);
  --chart-2: var(--saloora-rose);
  --chart-3: var(--saloora-sage);
  --chart-4: oklch(0.74 0.12 75);
  --chart-5: oklch(0.68 0.08 255);
  --sidebar: var(--saloora-paper);
  --sidebar-foreground: var(--saloora-plum);
  --sidebar-primary: var(--saloora-plum);
  --sidebar-primary-foreground: oklch(1 0 0);
  --sidebar-accent: var(--saloora-blush);
  --sidebar-accent-foreground: var(--saloora-plum);
  --sidebar-border: var(--border);
  --sidebar-ring: var(--saloora-rose);
${calendarColorOptions.map((option) => `  --calendar-${option.id}: ${option.light.oklch};`).join('\n')}
${lightCalendarVars.join('\n')}
${Object.entries(appointmentStatusPalettes)
  .flatMap(([status, palette]) => [
    `  --status-${status}-background: ${palette.background.oklch};`,
    `  --status-${status}-foreground: ${palette.foreground.oklch};`,
    `  --status-${status}-border: ${palette.border.oklch};`,
  ])
  .join('\n')}
  --radius: ${radiusRem.base};
}

.dark {
${cssVars('', semanticDark).join('\n')}
  --chart-1: var(--primary);
  --chart-2: var(--saloora-rose);
  --chart-3: oklch(0.7 0.06 150);
  --chart-4: oklch(0.74 0.12 75);
  --chart-5: oklch(0.7 0.08 255);
  --sidebar: var(--background);
  --sidebar-foreground: var(--foreground);
  --sidebar-primary: var(--primary);
  --sidebar-primary-foreground: var(--primary-foreground);
  --sidebar-accent: var(--accent);
  --sidebar-accent-foreground: var(--accent-foreground);
  --sidebar-border: var(--border);
  --sidebar-ring: var(--saloora-rose);
${calendarColorOptions.map((option) => `  --calendar-${option.id}: ${option.dark.oklch};`).join('\n')}
${darkCalendarVars.join('\n')}
}

@theme inline {
${themeColorVars.join('\n')}
  --font-sans: var(--font-vazirmatn), system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
  --font-mono: ui-monospace, 'SFMono-Regular', 'SF Mono', Consolas, monospace;
  --radius-sm: calc(var(--radius) - 4px);
  --radius-md: calc(var(--radius) - 2px);
  --radius-lg: var(--radius);
  --radius-xl: calc(var(--radius) + 4px);
}
`

const nativeTheme = {
  colors: {
    light: jsonReadyTokens(semanticLight),
    dark: jsonReadyTokens(semanticDark),
    brand: jsonReadyTokens(saloora),
    calendar: Object.fromEntries(
      calendarColorOptions.map((option) => [
        option.id,
        {
          labelFa: option.labelFa,
          light: option.light.hex,
          dark: option.dark.hex,
        },
      ]),
    ),
    appointmentStatus: Object.fromEntries(
      Object.entries(appointmentStatusPalettes).map(([status, palette]) => [
        status,
        {
          background: palette.background.hex,
          foreground: palette.foreground.hex,
          border: palette.border.hex,
        },
      ]),
    ),
  },
  radius: radiusPx,
  fontFamily,
}

await mkdir(generatedDir, { recursive: true })
await writeFile(join(generatedDir, 'web.css'), css)
await writeFile(
  join(generatedDir, 'native.ts'),
  `/* This file is generated by @repo/brand-tokens. Do not edit by hand. */

export const nativeTokens = ${JSON.stringify(nativeTheme, null, 2)} as const
`,
)
