/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SelectSalonRouteImport } from './routes/select-salon'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HandoffTokenRouteImport } from './routes/handoff.$token'
import { Route as AuthedTodayRouteImport } from './routes/_authed/today'
import { Route as AuthedSupportRouteImport } from './routes/_authed/support'
import { Route as AuthedStaffRouteImport } from './routes/_authed/staff'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedServicesRouteImport } from './routes/_authed/services'
import { Route as AuthedRetentionRouteImport } from './routes/_authed/retention'
import { Route as AuthedRequestsRouteImport } from './routes/_authed/requests'
import { Route as AuthedPublicPageRouteImport } from './routes/_authed/public-page'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedClientsRouteImport } from './routes/_authed/clients'
import { Route as AuthedCalendarRouteImport } from './routes/_authed/calendar'
import { Route as AuthedSupportIndexRouteImport } from './routes/_authed/support.index'
import { Route as AuthedStaffIndexRouteImport } from './routes/_authed/staff.index'
import { Route as AuthedOnboardingIndexRouteImport } from './routes/_authed/onboarding/index'
import { Route as AuthedClientsIndexRouteImport } from './routes/_authed/clients.index'
import { Route as AuthedSupportNewRouteImport } from './routes/_authed/support.new'
import { Route as AuthedSupportTicketIdRouteImport } from './routes/_authed/support.$ticketId'
import { Route as AuthedStaffIdRouteImport } from './routes/_authed/staff.$id'
import { Route as AuthedOnboardingWelcomeRouteImport } from './routes/_authed/onboarding/welcome'
import { Route as AuthedOnboardingStaffRouteImport } from './routes/_authed/onboarding/staff'
import { Route as AuthedOnboardingServicesRouteImport } from './routes/_authed/onboarding/services'
import { Route as AuthedOnboardingPublicRouteImport } from './routes/_authed/onboarding/public'
import { Route as AuthedOnboardingPresenceRouteImport } from './routes/_authed/onboarding/presence'
import { Route as AuthedOnboardingNotificationsRouteImport } from './routes/_authed/onboarding/notifications'
import { Route as AuthedOnboardingHoursRouteImport } from './routes/_authed/onboarding/hours'
import { Route as AuthedOnboardingDoneRouteImport } from './routes/_authed/onboarding/done'
import { Route as AuthedClientsImportRouteImport } from './routes/_authed/clients.import'
import { Route as AuthedClientsIdRouteImport } from './routes/_authed/clients.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectSalonRoute = SelectSalonRouteImport.update({
  id: '/select-salon',
  path: '/select-salon',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffTokenRoute = HandoffTokenRouteImport.update({
  id: '/handoff/$token',
  path: '/handoff/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTodayRoute = AuthedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSupportRoute = AuthedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStaffRoute = AuthedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedServicesRoute = AuthedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRetentionRoute = AuthedRetentionRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRequestsRoute = AuthedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPublicPageRoute = AuthedPublicPageRouteImport.update({
  id: '/public-page',
  path: '/public-page',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClientsRoute = AuthedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCalendarRoute = AuthedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSupportIndexRoute = AuthedSupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedSupportRoute,
} as any)
const AuthedStaffIndexRoute = AuthedStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedStaffRoute,
} as any)
const AuthedOnboardingIndexRoute = AuthedOnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedOnboardingRoute,
} as any)
const AuthedClientsIndexRoute = AuthedClientsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedClientsRoute,
} as any)
const AuthedSupportNewRoute = AuthedSupportNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthedSupportRoute,
} as any)
const AuthedSupportTicketIdRoute = AuthedSupportTicketIdRouteImport.update({
  id: '/$ticketId',
  path: '/$ticketId',
  getParentRoute: () => AuthedSupportRoute,
} as any)
const AuthedStaffIdRoute = AuthedStaffIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedStaffRoute,
} as any)
const AuthedOnboardingWelcomeRoute = AuthedOnboardingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthedOnboardingRoute,
} as any)
const AuthedOnboardingStaffRoute = AuthedOnboardingStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthedOnboardingRoute,
} as any)
const AuthedOnboardingServicesRoute =
  AuthedOnboardingServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthedOnboardingRoute,
  } as any)
const AuthedOnboardingPublicRoute = AuthedOnboardingPublicRouteImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => AuthedOnboardingRoute,
} as any)
const AuthedOnboardingPresenceRoute =
  AuthedOnboardingPresenceRouteImport.update({
    id: '/presence',
    path: '/presence',
    getParentRoute: () => AuthedOnboardingRoute,
  } as any)
const AuthedOnboardingNotificationsRoute =
  AuthedOnboardingNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthedOnboardingRoute,
  } as any)
const AuthedOnboardingHoursRoute = AuthedOnboardingHoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => AuthedOnboardingRoute,
} as any)
const AuthedOnboardingDoneRoute = AuthedOnboardingDoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => AuthedOnboardingRoute,
} as any)
const AuthedClientsImportRoute = AuthedClientsImportRouteImport.update({
  id: '/import',
  path: '/import',
  getParentRoute: () => AuthedClientsRoute,
} as any)
const AuthedClientsIdRoute = AuthedClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/select-salon': typeof SelectSalonRoute
  '/signup': typeof SignupRoute
  '/calendar': typeof AuthedCalendarRoute
  '/clients': typeof AuthedClientsRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/onboarding': typeof AuthedOnboardingRouteWithChildren
  '/public-page': typeof AuthedPublicPageRoute
  '/requests': typeof AuthedRequestsRoute
  '/retention': typeof AuthedRetentionRoute
  '/services': typeof AuthedServicesRoute
  '/settings': typeof AuthedSettingsRoute
  '/staff': typeof AuthedStaffRouteWithChildren
  '/support': typeof AuthedSupportRouteWithChildren
  '/today': typeof AuthedTodayRoute
  '/handoff/$token': typeof HandoffTokenRoute
  '/clients/$id': typeof AuthedClientsIdRoute
  '/clients/import': typeof AuthedClientsImportRoute
  '/onboarding/done': typeof AuthedOnboardingDoneRoute
  '/onboarding/hours': typeof AuthedOnboardingHoursRoute
  '/onboarding/notifications': typeof AuthedOnboardingNotificationsRoute
  '/onboarding/presence': typeof AuthedOnboardingPresenceRoute
  '/onboarding/public': typeof AuthedOnboardingPublicRoute
  '/onboarding/services': typeof AuthedOnboardingServicesRoute
  '/onboarding/staff': typeof AuthedOnboardingStaffRoute
  '/onboarding/welcome': typeof AuthedOnboardingWelcomeRoute
  '/staff/$id': typeof AuthedStaffIdRoute
  '/support/$ticketId': typeof AuthedSupportTicketIdRoute
  '/support/new': typeof AuthedSupportNewRoute
  '/clients/': typeof AuthedClientsIndexRoute
  '/onboarding/': typeof AuthedOnboardingIndexRoute
  '/staff/': typeof AuthedStaffIndexRoute
  '/support/': typeof AuthedSupportIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/select-salon': typeof SelectSalonRoute
  '/signup': typeof SignupRoute
  '/calendar': typeof AuthedCalendarRoute
  '/dashboard': typeof AuthedDashboardRoute
  '/public-page': typeof AuthedPublicPageRoute
  '/requests': typeof AuthedRequestsRoute
  '/retention': typeof AuthedRetentionRoute
  '/services': typeof AuthedServicesRoute
  '/settings': typeof AuthedSettingsRoute
  '/today': typeof AuthedTodayRoute
  '/handoff/$token': typeof HandoffTokenRoute
  '/clients/$id': typeof AuthedClientsIdRoute
  '/clients/import': typeof AuthedClientsImportRoute
  '/onboarding/done': typeof AuthedOnboardingDoneRoute
  '/onboarding/hours': typeof AuthedOnboardingHoursRoute
  '/onboarding/notifications': typeof AuthedOnboardingNotificationsRoute
  '/onboarding/presence': typeof AuthedOnboardingPresenceRoute
  '/onboarding/public': typeof AuthedOnboardingPublicRoute
  '/onboarding/services': typeof AuthedOnboardingServicesRoute
  '/onboarding/staff': typeof AuthedOnboardingStaffRoute
  '/onboarding/welcome': typeof AuthedOnboardingWelcomeRoute
  '/staff/$id': typeof AuthedStaffIdRoute
  '/support/$ticketId': typeof AuthedSupportTicketIdRoute
  '/support/new': typeof AuthedSupportNewRoute
  '/clients': typeof AuthedClientsIndexRoute
  '/onboarding': typeof AuthedOnboardingIndexRoute
  '/staff': typeof AuthedStaffIndexRoute
  '/support': typeof AuthedSupportIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/auth': typeof AuthRoute
  '/login': typeof LoginRoute
  '/select-salon': typeof SelectSalonRoute
  '/signup': typeof SignupRoute
  '/_authed/calendar': typeof AuthedCalendarRoute
  '/_authed/clients': typeof AuthedClientsRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/onboarding': typeof AuthedOnboardingRouteWithChildren
  '/_authed/public-page': typeof AuthedPublicPageRoute
  '/_authed/requests': typeof AuthedRequestsRoute
  '/_authed/retention': typeof AuthedRetentionRoute
  '/_authed/services': typeof AuthedServicesRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/staff': typeof AuthedStaffRouteWithChildren
  '/_authed/support': typeof AuthedSupportRouteWithChildren
  '/_authed/today': typeof AuthedTodayRoute
  '/handoff/$token': typeof HandoffTokenRoute
  '/_authed/clients/$id': typeof AuthedClientsIdRoute
  '/_authed/clients/import': typeof AuthedClientsImportRoute
  '/_authed/onboarding/done': typeof AuthedOnboardingDoneRoute
  '/_authed/onboarding/hours': typeof AuthedOnboardingHoursRoute
  '/_authed/onboarding/notifications': typeof AuthedOnboardingNotificationsRoute
  '/_authed/onboarding/presence': typeof AuthedOnboardingPresenceRoute
  '/_authed/onboarding/public': typeof AuthedOnboardingPublicRoute
  '/_authed/onboarding/services': typeof AuthedOnboardingServicesRoute
  '/_authed/onboarding/staff': typeof AuthedOnboardingStaffRoute
  '/_authed/onboarding/welcome': typeof AuthedOnboardingWelcomeRoute
  '/_authed/staff/$id': typeof AuthedStaffIdRoute
  '/_authed/support/$ticketId': typeof AuthedSupportTicketIdRoute
  '/_authed/support/new': typeof AuthedSupportNewRoute
  '/_authed/clients/': typeof AuthedClientsIndexRoute
  '/_authed/onboarding/': typeof AuthedOnboardingIndexRoute
  '/_authed/staff/': typeof AuthedStaffIndexRoute
  '/_authed/support/': typeof AuthedSupportIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/login'
    | '/select-salon'
    | '/signup'
    | '/calendar'
    | '/clients'
    | '/dashboard'
    | '/onboarding'
    | '/public-page'
    | '/requests'
    | '/retention'
    | '/services'
    | '/settings'
    | '/staff'
    | '/support'
    | '/today'
    | '/handoff/$token'
    | '/clients/$id'
    | '/clients/import'
    | '/onboarding/done'
    | '/onboarding/hours'
    | '/onboarding/notifications'
    | '/onboarding/presence'
    | '/onboarding/public'
    | '/onboarding/services'
    | '/onboarding/staff'
    | '/onboarding/welcome'
    | '/staff/$id'
    | '/support/$ticketId'
    | '/support/new'
    | '/clients/'
    | '/onboarding/'
    | '/staff/'
    | '/support/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/login'
    | '/select-salon'
    | '/signup'
    | '/calendar'
    | '/dashboard'
    | '/public-page'
    | '/requests'
    | '/retention'
    | '/services'
    | '/settings'
    | '/today'
    | '/handoff/$token'
    | '/clients/$id'
    | '/clients/import'
    | '/onboarding/done'
    | '/onboarding/hours'
    | '/onboarding/notifications'
    | '/onboarding/presence'
    | '/onboarding/public'
    | '/onboarding/services'
    | '/onboarding/staff'
    | '/onboarding/welcome'
    | '/staff/$id'
    | '/support/$ticketId'
    | '/support/new'
    | '/clients'
    | '/onboarding'
    | '/staff'
    | '/support'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/auth'
    | '/login'
    | '/select-salon'
    | '/signup'
    | '/_authed/calendar'
    | '/_authed/clients'
    | '/_authed/dashboard'
    | '/_authed/onboarding'
    | '/_authed/public-page'
    | '/_authed/requests'
    | '/_authed/retention'
    | '/_authed/services'
    | '/_authed/settings'
    | '/_authed/staff'
    | '/_authed/support'
    | '/_authed/today'
    | '/handoff/$token'
    | '/_authed/clients/$id'
    | '/_authed/clients/import'
    | '/_authed/onboarding/done'
    | '/_authed/onboarding/hours'
    | '/_authed/onboarding/notifications'
    | '/_authed/onboarding/presence'
    | '/_authed/onboarding/public'
    | '/_authed/onboarding/services'
    | '/_authed/onboarding/staff'
    | '/_authed/onboarding/welcome'
    | '/_authed/staff/$id'
    | '/_authed/support/$ticketId'
    | '/_authed/support/new'
    | '/_authed/clients/'
    | '/_authed/onboarding/'
    | '/_authed/staff/'
    | '/_authed/support/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  AuthRoute: typeof AuthRoute
  LoginRoute: typeof LoginRoute
  SelectSalonRoute: typeof SelectSalonRoute
  SignupRoute: typeof SignupRoute
  HandoffTokenRoute: typeof HandoffTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-salon': {
      id: '/select-salon'
      path: '/select-salon'
      fullPath: '/select-salon'
      preLoaderRoute: typeof SelectSalonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff/$token': {
      id: '/handoff/$token'
      path: '/handoff/$token'
      fullPath: '/handoff/$token'
      preLoaderRoute: typeof HandoffTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/today': {
      id: '/_authed/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthedTodayRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/support': {
      id: '/_authed/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthedSupportRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/staff': {
      id: '/_authed/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthedStaffRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/services': {
      id: '/_authed/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthedServicesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/retention': {
      id: '/_authed/retention'
      path: '/retention'
      fullPath: '/retention'
      preLoaderRoute: typeof AuthedRetentionRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/requests': {
      id: '/_authed/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthedRequestsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/public-page': {
      id: '/_authed/public-page'
      path: '/public-page'
      fullPath: '/public-page'
      preLoaderRoute: typeof AuthedPublicPageRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clients': {
      id: '/_authed/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthedClientsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/calendar': {
      id: '/_authed/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthedCalendarRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/support/': {
      id: '/_authed/support/'
      path: '/'
      fullPath: '/support/'
      preLoaderRoute: typeof AuthedSupportIndexRouteImport
      parentRoute: typeof AuthedSupportRoute
    }
    '/_authed/staff/': {
      id: '/_authed/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof AuthedStaffIndexRouteImport
      parentRoute: typeof AuthedStaffRoute
    }
    '/_authed/onboarding/': {
      id: '/_authed/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthedOnboardingIndexRouteImport
      parentRoute: typeof AuthedOnboardingRoute
    }
    '/_authed/clients/': {
      id: '/_authed/clients/'
      path: '/'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthedClientsIndexRouteImport
      parentRoute: typeof AuthedClientsRoute
    }
    '/_authed/support/new': {
      id: '/_authed/support/new'
      path: '/new'
      fullPath: '/support/new'
      preLoaderRoute: typeof AuthedSupportNewRouteImport
      parentRoute: typeof AuthedSupportRoute
    }
    '/_authed/support/$ticketId': {
      id: '/_authed/support/$ticketId'
      path: '/$ticketId'
      fullPath: '/support/$ticketId'
      preLoaderRoute: typeof AuthedSupportTicketIdRouteImport
      parentRoute: typeof AuthedSupportRoute
    }
    '/_authed/staff/$id': {
      id: '/_authed/staff/$id'
      path: '/$id'
      fullPath: '/staff/$id'
      preLoaderRoute: typeof AuthedStaffIdRouteImport
      parentRoute: typeof AuthedStaffRoute
    }
    '/_authed/onboarding/welcome': {
      id: '/_authed/onboarding/welcome'
      path: '/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof AuthedOnboardingWelcomeRouteImport
      parentRoute: typeof AuthedOnboardingRoute
    }
    '/_authed/onboarding/staff': {
      id: '/_authed/onboarding/staff'
      path: '/staff'
      fullPath: '/onboarding/staff'
      preLoaderRoute: typeof AuthedOnboardingStaffRouteImport
      parentRoute: typeof AuthedOnboardingRoute
    }
    '/_authed/onboarding/services': {
      id: '/_authed/onboarding/services'
      path: '/services'
      fullPath: '/onboarding/services'
      preLoaderRoute: typeof AuthedOnboardingServicesRouteImport
      parentRoute: typeof AuthedOnboardingRoute
    }
    '/_authed/onboarding/public': {
      id: '/_authed/onboarding/public'
      path: '/public'
      fullPath: '/onboarding/public'
      preLoaderRoute: typeof AuthedOnboardingPublicRouteImport
      parentRoute: typeof AuthedOnboardingRoute
    }
    '/_authed/onboarding/presence': {
      id: '/_authed/onboarding/presence'
      path: '/presence'
      fullPath: '/onboarding/presence'
      preLoaderRoute: typeof AuthedOnboardingPresenceRouteImport
      parentRoute: typeof AuthedOnboardingRoute
    }
    '/_authed/onboarding/notifications': {
      id: '/_authed/onboarding/notifications'
      path: '/notifications'
      fullPath: '/onboarding/notifications'
      preLoaderRoute: typeof AuthedOnboardingNotificationsRouteImport
      parentRoute: typeof AuthedOnboardingRoute
    }
    '/_authed/onboarding/hours': {
      id: '/_authed/onboarding/hours'
      path: '/hours'
      fullPath: '/onboarding/hours'
      preLoaderRoute: typeof AuthedOnboardingHoursRouteImport
      parentRoute: typeof AuthedOnboardingRoute
    }
    '/_authed/onboarding/done': {
      id: '/_authed/onboarding/done'
      path: '/done'
      fullPath: '/onboarding/done'
      preLoaderRoute: typeof AuthedOnboardingDoneRouteImport
      parentRoute: typeof AuthedOnboardingRoute
    }
    '/_authed/clients/import': {
      id: '/_authed/clients/import'
      path: '/import'
      fullPath: '/clients/import'
      preLoaderRoute: typeof AuthedClientsImportRouteImport
      parentRoute: typeof AuthedClientsRoute
    }
    '/_authed/clients/$id': {
      id: '/_authed/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthedClientsIdRouteImport
      parentRoute: typeof AuthedClientsRoute
    }
  }
}

interface AuthedClientsRouteChildren {
  AuthedClientsIdRoute: typeof AuthedClientsIdRoute
  AuthedClientsImportRoute: typeof AuthedClientsImportRoute
  AuthedClientsIndexRoute: typeof AuthedClientsIndexRoute
}

const AuthedClientsRouteChildren: AuthedClientsRouteChildren = {
  AuthedClientsIdRoute: AuthedClientsIdRoute,
  AuthedClientsImportRoute: AuthedClientsImportRoute,
  AuthedClientsIndexRoute: AuthedClientsIndexRoute,
}

const AuthedClientsRouteWithChildren = AuthedClientsRoute._addFileChildren(
  AuthedClientsRouteChildren,
)

interface AuthedOnboardingRouteChildren {
  AuthedOnboardingDoneRoute: typeof AuthedOnboardingDoneRoute
  AuthedOnboardingHoursRoute: typeof AuthedOnboardingHoursRoute
  AuthedOnboardingNotificationsRoute: typeof AuthedOnboardingNotificationsRoute
  AuthedOnboardingPresenceRoute: typeof AuthedOnboardingPresenceRoute
  AuthedOnboardingPublicRoute: typeof AuthedOnboardingPublicRoute
  AuthedOnboardingServicesRoute: typeof AuthedOnboardingServicesRoute
  AuthedOnboardingStaffRoute: typeof AuthedOnboardingStaffRoute
  AuthedOnboardingWelcomeRoute: typeof AuthedOnboardingWelcomeRoute
  AuthedOnboardingIndexRoute: typeof AuthedOnboardingIndexRoute
}

const AuthedOnboardingRouteChildren: AuthedOnboardingRouteChildren = {
  AuthedOnboardingDoneRoute: AuthedOnboardingDoneRoute,
  AuthedOnboardingHoursRoute: AuthedOnboardingHoursRoute,
  AuthedOnboardingNotificationsRoute: AuthedOnboardingNotificationsRoute,
  AuthedOnboardingPresenceRoute: AuthedOnboardingPresenceRoute,
  AuthedOnboardingPublicRoute: AuthedOnboardingPublicRoute,
  AuthedOnboardingServicesRoute: AuthedOnboardingServicesRoute,
  AuthedOnboardingStaffRoute: AuthedOnboardingStaffRoute,
  AuthedOnboardingWelcomeRoute: AuthedOnboardingWelcomeRoute,
  AuthedOnboardingIndexRoute: AuthedOnboardingIndexRoute,
}

const AuthedOnboardingRouteWithChildren =
  AuthedOnboardingRoute._addFileChildren(AuthedOnboardingRouteChildren)

interface AuthedStaffRouteChildren {
  AuthedStaffIdRoute: typeof AuthedStaffIdRoute
  AuthedStaffIndexRoute: typeof AuthedStaffIndexRoute
}

const AuthedStaffRouteChildren: AuthedStaffRouteChildren = {
  AuthedStaffIdRoute: AuthedStaffIdRoute,
  AuthedStaffIndexRoute: AuthedStaffIndexRoute,
}

const AuthedStaffRouteWithChildren = AuthedStaffRoute._addFileChildren(
  AuthedStaffRouteChildren,
)

interface AuthedSupportRouteChildren {
  AuthedSupportTicketIdRoute: typeof AuthedSupportTicketIdRoute
  AuthedSupportNewRoute: typeof AuthedSupportNewRoute
  AuthedSupportIndexRoute: typeof AuthedSupportIndexRoute
}

const AuthedSupportRouteChildren: AuthedSupportRouteChildren = {
  AuthedSupportTicketIdRoute: AuthedSupportTicketIdRoute,
  AuthedSupportNewRoute: AuthedSupportNewRoute,
  AuthedSupportIndexRoute: AuthedSupportIndexRoute,
}

const AuthedSupportRouteWithChildren = AuthedSupportRoute._addFileChildren(
  AuthedSupportRouteChildren,
)

interface AuthedRouteChildren {
  AuthedCalendarRoute: typeof AuthedCalendarRoute
  AuthedClientsRoute: typeof AuthedClientsRouteWithChildren
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedOnboardingRoute: typeof AuthedOnboardingRouteWithChildren
  AuthedPublicPageRoute: typeof AuthedPublicPageRoute
  AuthedRequestsRoute: typeof AuthedRequestsRoute
  AuthedRetentionRoute: typeof AuthedRetentionRoute
  AuthedServicesRoute: typeof AuthedServicesRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedStaffRoute: typeof AuthedStaffRouteWithChildren
  AuthedSupportRoute: typeof AuthedSupportRouteWithChildren
  AuthedTodayRoute: typeof AuthedTodayRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCalendarRoute: AuthedCalendarRoute,
  AuthedClientsRoute: AuthedClientsRouteWithChildren,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedOnboardingRoute: AuthedOnboardingRouteWithChildren,
  AuthedPublicPageRoute: AuthedPublicPageRoute,
  AuthedRequestsRoute: AuthedRequestsRoute,
  AuthedRetentionRoute: AuthedRetentionRoute,
  AuthedServicesRoute: AuthedServicesRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedStaffRoute: AuthedStaffRouteWithChildren,
  AuthedSupportRoute: AuthedSupportRouteWithChildren,
  AuthedTodayRoute: AuthedTodayRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  AuthRoute: AuthRoute,
  LoginRoute: LoginRoute,
  SelectSalonRoute: SelectSalonRoute,
  SignupRoute: SignupRoute,
  HandoffTokenRoute: HandoffTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
