/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthedTodayRouteImport } from './routes/_authed/today'
import { Route as AuthedStaffRouteImport } from './routes/_authed/staff'
import { Route as AuthedSettingsRouteImport } from './routes/_authed/settings'
import { Route as AuthedServicesRouteImport } from './routes/_authed/services'
import { Route as AuthedRetentionRouteImport } from './routes/_authed/retention'
import { Route as AuthedRequestsRouteImport } from './routes/_authed/requests'
import { Route as AuthedPublicPageRouteImport } from './routes/_authed/public-page'
import { Route as AuthedOnboardingRouteImport } from './routes/_authed/onboarding'
import { Route as AuthedDashboardRouteImport } from './routes/_authed/dashboard'
import { Route as AuthedClientsRouteImport } from './routes/_authed/clients'
import { Route as AuthedCalendarRouteImport } from './routes/_authed/calendar'
import { Route as AuthedOnboardingIndexRouteImport } from './routes/_authed/onboarding/index'
import { Route as AuthedOnboardingWelcomeRouteImport } from './routes/_authed/onboarding/welcome'
import { Route as AuthedOnboardingStaffRouteImport } from './routes/_authed/onboarding/staff'
import { Route as AuthedOnboardingServicesRouteImport } from './routes/_authed/onboarding/services'
import { Route as AuthedOnboardingPublicRouteImport } from './routes/_authed/onboarding/public'
import { Route as AuthedOnboardingPresenceRouteImport } from './routes/_authed/onboarding/presence'
import { Route as AuthedOnboardingNotificationsRouteImport } from './routes/_authed/onboarding/notifications'
import { Route as AuthedOnboardingHoursRouteImport } from './routes/_authed/onboarding/hours'
import { Route as AuthedOnboardingDoneRouteImport } from './routes/_authed/onboarding/done'
import { Route as AuthedClientsIdRouteImport } from './routes/_authed/clients.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedTodayRoute = AuthedTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedStaffRoute = AuthedStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsRoute = AuthedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedServicesRoute = AuthedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRetentionRoute = AuthedRetentionRouteImport.update({
  id: '/retention',
  path: '/retention',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedRequestsRoute = AuthedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedPublicPageRoute = AuthedPublicPageRouteImport.update({
  id: '/public-page',
  path: '/public-page',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingRoute = AuthedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedDashboardRoute = AuthedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClientsRoute = AuthedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedCalendarRoute = AuthedCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedOnboardingIndexRoute = AuthedOnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedOnboardingRoute,
} as any)
const AuthedOnboardingWelcomeRoute = AuthedOnboardingWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AuthedOnboardingRoute,
} as any)
const AuthedOnboardingStaffRoute = AuthedOnboardingStaffRouteImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => AuthedOnboardingRoute,
} as any)
const AuthedOnboardingServicesRoute =
  AuthedOnboardingServicesRouteImport.update({
    id: '/services',
    path: '/services',
    getParentRoute: () => AuthedOnboardingRoute,
  } as any)
const AuthedOnboardingPublicRoute = AuthedOnboardingPublicRouteImport.update({
  id: '/public',
  path: '/public',
  getParentRoute: () => AuthedOnboardingRoute,
} as any)
const AuthedOnboardingPresenceRoute =
  AuthedOnboardingPresenceRouteImport.update({
    id: '/presence',
    path: '/presence',
    getParentRoute: () => AuthedOnboardingRoute,
  } as any)
const AuthedOnboardingNotificationsRoute =
  AuthedOnboardingNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthedOnboardingRoute,
  } as any)
const AuthedOnboardingHoursRoute = AuthedOnboardingHoursRouteImport.update({
  id: '/hours',
  path: '/hours',
  getParentRoute: () => AuthedOnboardingRoute,
} as any)
const AuthedOnboardingDoneRoute = AuthedOnboardingDoneRouteImport.update({
  id: '/done',
  path: '/done',
  getParentRoute: () => AuthedOnboardingRoute,
} as any)
const AuthedClientsIdRoute = AuthedClientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthedClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/calendar': typeof AuthedCalendarRoute
  '/clients': typeof AuthedClientsRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/onboarding': typeof AuthedOnboardingRouteWithChildren
  '/public-page': typeof AuthedPublicPageRoute
  '/requests': typeof AuthedRequestsRoute
  '/retention': typeof AuthedRetentionRoute
  '/services': typeof AuthedServicesRoute
  '/settings': typeof AuthedSettingsRoute
  '/staff': typeof AuthedStaffRoute
  '/today': typeof AuthedTodayRoute
  '/clients/$id': typeof AuthedClientsIdRoute
  '/onboarding/done': typeof AuthedOnboardingDoneRoute
  '/onboarding/hours': typeof AuthedOnboardingHoursRoute
  '/onboarding/notifications': typeof AuthedOnboardingNotificationsRoute
  '/onboarding/presence': typeof AuthedOnboardingPresenceRoute
  '/onboarding/public': typeof AuthedOnboardingPublicRoute
  '/onboarding/services': typeof AuthedOnboardingServicesRoute
  '/onboarding/staff': typeof AuthedOnboardingStaffRoute
  '/onboarding/welcome': typeof AuthedOnboardingWelcomeRoute
  '/onboarding/': typeof AuthedOnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/calendar': typeof AuthedCalendarRoute
  '/clients': typeof AuthedClientsRouteWithChildren
  '/dashboard': typeof AuthedDashboardRoute
  '/public-page': typeof AuthedPublicPageRoute
  '/requests': typeof AuthedRequestsRoute
  '/retention': typeof AuthedRetentionRoute
  '/services': typeof AuthedServicesRoute
  '/settings': typeof AuthedSettingsRoute
  '/staff': typeof AuthedStaffRoute
  '/today': typeof AuthedTodayRoute
  '/clients/$id': typeof AuthedClientsIdRoute
  '/onboarding/done': typeof AuthedOnboardingDoneRoute
  '/onboarding/hours': typeof AuthedOnboardingHoursRoute
  '/onboarding/notifications': typeof AuthedOnboardingNotificationsRoute
  '/onboarding/presence': typeof AuthedOnboardingPresenceRoute
  '/onboarding/public': typeof AuthedOnboardingPublicRoute
  '/onboarding/services': typeof AuthedOnboardingServicesRoute
  '/onboarding/staff': typeof AuthedOnboardingStaffRoute
  '/onboarding/welcome': typeof AuthedOnboardingWelcomeRoute
  '/onboarding': typeof AuthedOnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/calendar': typeof AuthedCalendarRoute
  '/_authed/clients': typeof AuthedClientsRouteWithChildren
  '/_authed/dashboard': typeof AuthedDashboardRoute
  '/_authed/onboarding': typeof AuthedOnboardingRouteWithChildren
  '/_authed/public-page': typeof AuthedPublicPageRoute
  '/_authed/requests': typeof AuthedRequestsRoute
  '/_authed/retention': typeof AuthedRetentionRoute
  '/_authed/services': typeof AuthedServicesRoute
  '/_authed/settings': typeof AuthedSettingsRoute
  '/_authed/staff': typeof AuthedStaffRoute
  '/_authed/today': typeof AuthedTodayRoute
  '/_authed/clients/$id': typeof AuthedClientsIdRoute
  '/_authed/onboarding/done': typeof AuthedOnboardingDoneRoute
  '/_authed/onboarding/hours': typeof AuthedOnboardingHoursRoute
  '/_authed/onboarding/notifications': typeof AuthedOnboardingNotificationsRoute
  '/_authed/onboarding/presence': typeof AuthedOnboardingPresenceRoute
  '/_authed/onboarding/public': typeof AuthedOnboardingPublicRoute
  '/_authed/onboarding/services': typeof AuthedOnboardingServicesRoute
  '/_authed/onboarding/staff': typeof AuthedOnboardingStaffRoute
  '/_authed/onboarding/welcome': typeof AuthedOnboardingWelcomeRoute
  '/_authed/onboarding/': typeof AuthedOnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/calendar'
    | '/clients'
    | '/dashboard'
    | '/onboarding'
    | '/public-page'
    | '/requests'
    | '/retention'
    | '/services'
    | '/settings'
    | '/staff'
    | '/today'
    | '/clients/$id'
    | '/onboarding/done'
    | '/onboarding/hours'
    | '/onboarding/notifications'
    | '/onboarding/presence'
    | '/onboarding/public'
    | '/onboarding/services'
    | '/onboarding/staff'
    | '/onboarding/welcome'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/calendar'
    | '/clients'
    | '/dashboard'
    | '/public-page'
    | '/requests'
    | '/retention'
    | '/services'
    | '/settings'
    | '/staff'
    | '/today'
    | '/clients/$id'
    | '/onboarding/done'
    | '/onboarding/hours'
    | '/onboarding/notifications'
    | '/onboarding/presence'
    | '/onboarding/public'
    | '/onboarding/services'
    | '/onboarding/staff'
    | '/onboarding/welcome'
    | '/onboarding'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/signup'
    | '/_authed/calendar'
    | '/_authed/clients'
    | '/_authed/dashboard'
    | '/_authed/onboarding'
    | '/_authed/public-page'
    | '/_authed/requests'
    | '/_authed/retention'
    | '/_authed/services'
    | '/_authed/settings'
    | '/_authed/staff'
    | '/_authed/today'
    | '/_authed/clients/$id'
    | '/_authed/onboarding/done'
    | '/_authed/onboarding/hours'
    | '/_authed/onboarding/notifications'
    | '/_authed/onboarding/presence'
    | '/_authed/onboarding/public'
    | '/_authed/onboarding/services'
    | '/_authed/onboarding/staff'
    | '/_authed/onboarding/welcome'
    | '/_authed/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/today': {
      id: '/_authed/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AuthedTodayRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/staff': {
      id: '/_authed/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof AuthedStaffRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings': {
      id: '/_authed/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/services': {
      id: '/_authed/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthedServicesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/retention': {
      id: '/_authed/retention'
      path: '/retention'
      fullPath: '/retention'
      preLoaderRoute: typeof AuthedRetentionRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/requests': {
      id: '/_authed/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthedRequestsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/public-page': {
      id: '/_authed/public-page'
      path: '/public-page'
      fullPath: '/public-page'
      preLoaderRoute: typeof AuthedPublicPageRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding': {
      id: '/_authed/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedOnboardingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/dashboard': {
      id: '/_authed/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthedDashboardRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clients': {
      id: '/_authed/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthedClientsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/calendar': {
      id: '/_authed/calendar'
      path: '/calendar'
      fullPath: '/calendar'
      preLoaderRoute: typeof AuthedCalendarRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/onboarding/': {
      id: '/_authed/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthedOnboardingIndexRouteImport
      parentRoute: typeof AuthedOnboardingRoute
    }
    '/_authed/onboarding/welcome': {
      id: '/_authed/onboarding/welcome'
      path: '/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof AuthedOnboardingWelcomeRouteImport
      parentRoute: typeof AuthedOnboardingRoute
    }
    '/_authed/onboarding/staff': {
      id: '/_authed/onboarding/staff'
      path: '/staff'
      fullPath: '/onboarding/staff'
      preLoaderRoute: typeof AuthedOnboardingStaffRouteImport
      parentRoute: typeof AuthedOnboardingRoute
    }
    '/_authed/onboarding/services': {
      id: '/_authed/onboarding/services'
      path: '/services'
      fullPath: '/onboarding/services'
      preLoaderRoute: typeof AuthedOnboardingServicesRouteImport
      parentRoute: typeof AuthedOnboardingRoute
    }
    '/_authed/onboarding/public': {
      id: '/_authed/onboarding/public'
      path: '/public'
      fullPath: '/onboarding/public'
      preLoaderRoute: typeof AuthedOnboardingPublicRouteImport
      parentRoute: typeof AuthedOnboardingRoute
    }
    '/_authed/onboarding/presence': {
      id: '/_authed/onboarding/presence'
      path: '/presence'
      fullPath: '/onboarding/presence'
      preLoaderRoute: typeof AuthedOnboardingPresenceRouteImport
      parentRoute: typeof AuthedOnboardingRoute
    }
    '/_authed/onboarding/notifications': {
      id: '/_authed/onboarding/notifications'
      path: '/notifications'
      fullPath: '/onboarding/notifications'
      preLoaderRoute: typeof AuthedOnboardingNotificationsRouteImport
      parentRoute: typeof AuthedOnboardingRoute
    }
    '/_authed/onboarding/hours': {
      id: '/_authed/onboarding/hours'
      path: '/hours'
      fullPath: '/onboarding/hours'
      preLoaderRoute: typeof AuthedOnboardingHoursRouteImport
      parentRoute: typeof AuthedOnboardingRoute
    }
    '/_authed/onboarding/done': {
      id: '/_authed/onboarding/done'
      path: '/done'
      fullPath: '/onboarding/done'
      preLoaderRoute: typeof AuthedOnboardingDoneRouteImport
      parentRoute: typeof AuthedOnboardingRoute
    }
    '/_authed/clients/$id': {
      id: '/_authed/clients/$id'
      path: '/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthedClientsIdRouteImport
      parentRoute: typeof AuthedClientsRoute
    }
  }
}

interface AuthedClientsRouteChildren {
  AuthedClientsIdRoute: typeof AuthedClientsIdRoute
}

const AuthedClientsRouteChildren: AuthedClientsRouteChildren = {
  AuthedClientsIdRoute: AuthedClientsIdRoute,
}

const AuthedClientsRouteWithChildren = AuthedClientsRoute._addFileChildren(
  AuthedClientsRouteChildren,
)

interface AuthedOnboardingRouteChildren {
  AuthedOnboardingDoneRoute: typeof AuthedOnboardingDoneRoute
  AuthedOnboardingHoursRoute: typeof AuthedOnboardingHoursRoute
  AuthedOnboardingNotificationsRoute: typeof AuthedOnboardingNotificationsRoute
  AuthedOnboardingPresenceRoute: typeof AuthedOnboardingPresenceRoute
  AuthedOnboardingPublicRoute: typeof AuthedOnboardingPublicRoute
  AuthedOnboardingServicesRoute: typeof AuthedOnboardingServicesRoute
  AuthedOnboardingStaffRoute: typeof AuthedOnboardingStaffRoute
  AuthedOnboardingWelcomeRoute: typeof AuthedOnboardingWelcomeRoute
  AuthedOnboardingIndexRoute: typeof AuthedOnboardingIndexRoute
}

const AuthedOnboardingRouteChildren: AuthedOnboardingRouteChildren = {
  AuthedOnboardingDoneRoute: AuthedOnboardingDoneRoute,
  AuthedOnboardingHoursRoute: AuthedOnboardingHoursRoute,
  AuthedOnboardingNotificationsRoute: AuthedOnboardingNotificationsRoute,
  AuthedOnboardingPresenceRoute: AuthedOnboardingPresenceRoute,
  AuthedOnboardingPublicRoute: AuthedOnboardingPublicRoute,
  AuthedOnboardingServicesRoute: AuthedOnboardingServicesRoute,
  AuthedOnboardingStaffRoute: AuthedOnboardingStaffRoute,
  AuthedOnboardingWelcomeRoute: AuthedOnboardingWelcomeRoute,
  AuthedOnboardingIndexRoute: AuthedOnboardingIndexRoute,
}

const AuthedOnboardingRouteWithChildren =
  AuthedOnboardingRoute._addFileChildren(AuthedOnboardingRouteChildren)

interface AuthedRouteChildren {
  AuthedCalendarRoute: typeof AuthedCalendarRoute
  AuthedClientsRoute: typeof AuthedClientsRouteWithChildren
  AuthedDashboardRoute: typeof AuthedDashboardRoute
  AuthedOnboardingRoute: typeof AuthedOnboardingRouteWithChildren
  AuthedPublicPageRoute: typeof AuthedPublicPageRoute
  AuthedRequestsRoute: typeof AuthedRequestsRoute
  AuthedRetentionRoute: typeof AuthedRetentionRoute
  AuthedServicesRoute: typeof AuthedServicesRoute
  AuthedSettingsRoute: typeof AuthedSettingsRoute
  AuthedStaffRoute: typeof AuthedStaffRoute
  AuthedTodayRoute: typeof AuthedTodayRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedCalendarRoute: AuthedCalendarRoute,
  AuthedClientsRoute: AuthedClientsRouteWithChildren,
  AuthedDashboardRoute: AuthedDashboardRoute,
  AuthedOnboardingRoute: AuthedOnboardingRouteWithChildren,
  AuthedPublicPageRoute: AuthedPublicPageRoute,
  AuthedRequestsRoute: AuthedRequestsRoute,
  AuthedRetentionRoute: AuthedRetentionRoute,
  AuthedServicesRoute: AuthedServicesRoute,
  AuthedSettingsRoute: AuthedSettingsRoute,
  AuthedStaffRoute: AuthedStaffRoute,
  AuthedTodayRoute: AuthedTodayRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
