export {
  getAllStaff,
  countManagers,
  deactivateStaffMember,
  getStaffBookingAvailabilityForSlot,
  getStaffScheduleForDay,
  getStaffScheduleForDayAnyStatus,
  getStaffSchedules,
  getUserWithServiceIds,
  setStaffSchedules,
  setStaffServiceIds,
  staffMayPerformService,
  findSoleCapableStaffUserId,
  listCapableStaffForService,
  updateStaffMember,
  updateStaffPassword,
} from './internal/staff-queries'

export { getUserById } from './internal/user-queries'
export { getBusinessSettings } from './internal/settings-queries'
export { validateActiveServiceIds } from './internal/service-queries'
export {
  claimStaffProfile,
  createSetupStaffProfile,
  getStaffProfileForUser,
  getClaimedStaffAccessForPhone,
  listSetupStaffProfiles,
} from './setup-staff'
export {
  cancelManagerStaffInvite,
  createManagerStaffInvite,
  deliverStaffInvite,
  evaluateCancelManagerStaffInvite,
  evaluateManagerStaffInvite,
  evaluateResendManagerStaffInvite,
  evaluateStaffInviteLinkRouting,
  getPendingStaffInviteForProfile,
  listPendingStaffInvitesForSalon,
  resendManagerStaffInvite,
  resolveStaffInviteByToken,
  resolveStaffInvitePhonesMatch,
  STAFF_INVITE_TTL_MS,
  type CancelManagerStaffInviteRejectionReason,
  type CancelManagerStaffInviteResult,
  type CreateManagerStaffInviteInput,
  type CreateManagerStaffInviteResult,
  type ManagerStaffInviteDecision,
  type ManagerStaffInviteRejectionReason,
  type ResendManagerStaffInviteRejectionReason,
  type ResendManagerStaffInviteResult,
  type ResolveStaffInviteByTokenResult,
  type StaffInviteDeliveryChannel,
  type StaffInviteDeliveryResult,
  type StaffInviteLinkView,
  maskStaffInvitePhone,
} from './staff-invites'
export {
  acceptStaffInvite,
  declineStaffInvite,
  evaluateStaffInviteAcceptance,
  evaluateStaffInviteDecline,
  listPendingStaffInvitesForUser,
  type AcceptStaffInviteResult,
  type DeclineStaffInviteResult,
  type PendingStaffInviteView,
  type StaffInviteAcceptanceRejectionReason,
  type StaffInviteDeclineRejectionReason,
} from './staff-invite-acceptance'
export {
  evaluateStaffTenantAccess,
  listActiveStaffProfileAccessesForUser,
  resolveStaffTenantContext,
  type ActiveStaffProfileAccessSnapshot,
  type ResolveStaffTenantContextResult,
  type StaffTenantAccessDecision,
  type StaffTenantAccessRejectionReason,
} from './staff-profile-access'
