FROM docker:29.1.2-cli AS docker
FROM python:3.12-alpine
COPY --from=docker /usr/local/bin/docker /usr/local/bin/docker
COPY --from=docker /usr/local/libexec/docker/cli-plugins/docker-compose /usr/local/libexec/docker/cli-plugins/docker-compose
COPY deploy/qa/control.py /control.py
CMD ["python", "/control.py"]
