server {
  listen 8080;
  server_name staging-app.saluna.ir;
  location /api/ { proxy_pass http://saluna-qa-api:3002; proxy_set_header Host $host; proxy_set_header X-Forwarded-Proto https; }
  location = /health { proxy_pass http://saluna-qa-api:3002/health; }
  location / { proxy_pass http://saluna-qa-pwa:80; proxy_set_header Host $host; }
}
server {
  listen 8080;
  server_name staging.saluna.ir;
  location /api/ { proxy_pass http://saluna-qa-api:3002; proxy_set_header Host $host; proxy_set_header X-Forwarded-Proto https; }
  location / { proxy_pass http://saluna-qa-web:3001; proxy_set_header Host $host; proxy_set_header X-Forwarded-Proto https; }
}
server {
  listen 8080;
  server_name staging-api.saluna.ir;
  location / { proxy_pass http://saluna-qa-api:3002; proxy_set_header Host $host; proxy_set_header X-Forwarded-Proto https; }
}
